import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import StoreNavbar from '@/components/StoreNavbar';
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    fetch(`https://fakestoreapi.com/products`)
      .then(res => res.json())
      .then(data => {
        setProducts(data);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Seneca Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav className={styles.navbar}>
          <StoreNavbar />
        </nav>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <Image
            src="/senecaStore.png"
            alt="Seneca Store"
            width={700}
            height={100}
          />
          <div className={`${styles.code}`}>
            <br />
            &nbsp; &nbsp; &nbsp; &nbsp;Welcome to Seneca, your premier destination for stylish clothing and trendy bags.<br />
            Explore our curated selection to discover fashion that blends elegance with everyday comfort.<br /><br />
          </div>
          <div className={`${styles.code}`}>
            Our Favourites
          </div>
          <div className={styles.galleryFlex}>
            {products.slice(0, 6).map(product => (
              <div key={product.id} className={styles.product}>
                <h3>{product.title}</h3>
                <p>{product.description}</p>
                <img
                  src={product.image}
                  alt={product.title}
                  width={200}
                  height={200}
                />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
